#!/usr/bin/env bash
./plot_z25.py --data_file sfcvm.txt --meta_file sfcvm_meta.txt --output_file sf_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for USGS SFB Region CVM"
./plot_z25.py --data_file canvas.txt --meta_file canvas_meta.txt --output_file canvas_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for CANVAS CVM"
./plot_z25.py --data_file uwlinca.txt --meta_file uwlinca_meta.txt --output_file uwlinca_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for U.W. Lin Thurber CVM"
./plot_z25.py --data_file uwsfbcvm.txt --meta_file uwsfbcvm_meta.txt --output_file uwsfb_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for U.W. SF CVM"
./plot_z25.py --data_file cs248.txt --meta_file cs248_meta.txt --output_file cs248_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for cs248 CVM"
./plot_z25.py --data_file cvmh.txt --meta_file cvmh_meta.txt --output_file cvmh_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for CVM-H"
./plot_z25.py --data_file sjfz.txt --meta_file sjfz_meta.txt --output_file sjfz_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for San Jacinto Fault Zone CVM"
./plot_z25.py --data_file cvms.txt --meta_file cvms_meta.txt --output_file cvms_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for CVM-S4"
./plot_z25.py --data_file cvms5.txt --meta_file cvms5_meta.txt --output_file cvms5_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for CVM-S4.26"
./plot_z25.py --data_file cvmsi.txt --meta_file cvmsi_meta.txt --output_file cvmsi_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for CVM-S4.26.M01"
./plot_z25.py --data_file ssip.txt --meta_file ssip_meta.txt --output_file ssip_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for SSIP Imperial Valley and Coachella CVMs"
./plot_z25.py --data_file albacore.txt --meta_file albacore_meta.txt --output_file albacore_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for ALBACORE"
./plot_z25.py --data_file basins.txt --meta_file basins_meta.txt --output_file basins_output.png --scale_mode user --user_max 3000 --cmap jet --alpha 0.6 --title "Z1.0 Map for SoCal Harvard Basin Models"